<?php

use App\Municipio;
use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipio::create(['nombre' => 'Sin municipio', 'departamento_id' => '15']);
        Municipio::create(['nombre' => 'Ahuachapán', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Jujutla', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Atiquizaya', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Concepción de Ataco ', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'El Refugio' , 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Guaymango',  'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Apaneca',  'departamento_id' => '1']);
        Municipio::create(['nombre' => 'San Francisco Menéndez ', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'San Lorenzo' , 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'San Pedro Puxtla ', 'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Tacuba',  'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Turín',  'departamento_id' => '1']);
        Municipio::create(['nombre' => 'Candelaria de la  Frontera', 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Chalchuapa',  'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Coatepeque',  'departamento_id' => '2']);
        Municipio::create(['nombre' => 'El Congo' , 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'El Porvenir' , 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Masahuat',  'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Metapán',  'departamento_id' => '2']);
        Municipio::create(['nombre' => 'San Antonio Pajonal ', 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'San Sebastián Salitrillo ', 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Santa Ana' , 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Santa Rosa Guachipilín ', 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Santiago de la  Frontera', 'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Texistepeque',  'departamento_id' => '2']);
        Municipio::create(['nombre' => 'Acajutla',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Armenia',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Caluco',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Cuisnahuat',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Izalco',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Juayúa',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Nahuizalco',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Nahulingo',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Salcoatitán',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'San Antonio del  Monte', 'departamento_id' => '3']);
        Municipio::create(['nombre' => 'San Julián' , 'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Santa Catarina Masahuat ', 'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Santa Isabel Ishuatán ', 'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Santo Domingo de  Guzmán', 'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Sonsonate',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Sonzacate',  'departamento_id' => '3']);
        Municipio::create(['nombre' => 'Alegría',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Berlín',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'California',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Concepción Batres' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'El Triunfo' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Ereguayquín',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Estanzuelas',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Jiquilisco',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Jucuapa',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Jucuarán',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Mercedes Umaña' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Nueva Granada' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Ozatlán',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Puerto El Triunfo ', 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'San Agustín' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'San Buenaventura' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'San Dionisio' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'San Francisco Javier ', 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Santa Elena' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Santa María' , 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Santiago de María ', 'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Tecapán',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Usulután',  'departamento_id' => '11']);
        Municipio::create(['nombre' => 'Carolina',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Chapeltique',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Chinameca',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Chirilagua',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Ciudad Barrios' , 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Comacarán',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'El Tránsito' , 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Lolotique',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Moncagua',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Nueva Guadalupe' , 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Nuevo Edén de  San Juan', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Quelepa',  'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Antonio del  Mosco', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Gerardo' , 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Jorge' , 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Luis de  la Reina', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Miguel', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'San Rafael Oriente', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Sesori', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Uluazapa', 'departamento_id' => '13']);
        Municipio::create(['nombre' => 'Arambala', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Cacaopera', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Chilanga', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Corinto', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Delicias de Concepción', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'El Divisadero', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'El Rosario (Morazán)', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Gualococti', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Guatajiagua', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Joateca', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Jocoaitique', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Jocoro', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Lolotiquillo', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Meanguera', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Osicala', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Perquín', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'San Carlos', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'San Fernando (Morazán)', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'San Francisco Gotera', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'San Isidro (Morazán)', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'San Simón', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Sensembra', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Sociedad', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Torola', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Yamabal', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'Yoloaiquín', 'departamento_id' => '12']);
        Municipio::create(['nombre' => 'La Unión', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'San Alejo', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Yucuaiquín', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Conchagua', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Intipucá', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'San José', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'El Carmen (La Unión)', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Yayantique', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Bolívar', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Meanguera del Golfo', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Santa Rosa de Lima', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Pasaquina', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Anamoros', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Nueva Esparta', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'El Sauce', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Concepción de Oriente', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Polorós', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Lislique', 'departamento_id' => '14']);
        Municipio::create(['nombre' => 'Antiguo Cuscatlán', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Chiltiupán', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Ciudad Arce', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Colón', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Comasagua', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Huizúcar', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Jayaque', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Jicalapa', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'La Libertad', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Santa Tecla', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Nuevo Cuscatlán', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'San Juan Opico', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Quezaltepeque', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Sacacoyo', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'San José Villanueva', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'San Matías', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'San Pablo Tacachico', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Talnique', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Tamanique', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Teotepeque', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Tepecoyo', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Zaragoza', 'departamento_id' => '4']);
        Municipio::create(['nombre' => 'Agua Caliente', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Arcatao', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Azacualpa', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Cancasque', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Chalatenango', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Citalá', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Comapala', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Concepción Quezaltepeque', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Dulce Nombre de María', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'El Carrizal', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'El Paraíso', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'La Laguna', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'La Palma', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'La Reina', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Las Vueltas', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Nueva Concepción', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Nueva Trinidad', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Nombre de Jesús', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Ojos de Agua', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Potonico', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Antonio de la Cruz', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Antonio Los Ranchos', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Fernando (Chalatenango)', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Francisco Lempa', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Francisco Morazán', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Ignacio', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Isidro Labrador', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Las Flores', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Luis del Carmen', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Miguel de Mercedes', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'San Rafael', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Santa Rita', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Tejutla', 'departamento_id' => '5']);
        Municipio::create(['nombre' => 'Cojutepeque', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Candelaria', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'El Carmen (Cuscatlán)', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'El Rosario (Cuscatlán)', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Monte San Juan', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Oratorio de Concepción', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San Bartolomé Perulapía', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San Cristóbal', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San José Guayabal', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San Pedro Perulapán', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San Rafael Cedros', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'San Ramón', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Santa Cruz Analquito', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Santa Cruz Michapa', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Suchitoto', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Tenancingo', 'departamento_id' => '7']);
        Municipio::create(['nombre' => 'Aguilares', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Apopa', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Ayutuxtepeque', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Cuscatancingo', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Ciudad Delgado', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'El Paisnal', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Guazapa', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Ilopango', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Mejicanos', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Nejapa', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Panchimalco', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Rosario de Mora', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'San Marcos', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'San Martín', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'San Salvador', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Santiago Texacuangos', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Santo Tomás', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Soyapango', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Tonacatepeque', 'departamento_id' => '6']);
        Municipio::create(['nombre' => 'Zacatecoluca', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Cuyultitán', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'El Rosario (La Paz)', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Jerusalén', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Mercedes La Ceiba', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Olocuilta', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Paraíso de Osorio', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Antonio Masahuat', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Emigdio', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Francisco Chinameca', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Pedro Masahuat', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Juan Nonualco', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Juan Talpa', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Juan Tepezontes', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Luis La Herradura', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Luis Talpa', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Miguel Tepezontes', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Pedro Nonualco', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'San Rafael Obrajuelo', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Santa María Ostuma', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Santiago Nonualco', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Tapalhuaca', 'departamento_id' => '8']);
        Municipio::create(['nombre' => 'Cinquera', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Dolores', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Guacotecti', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Ilobasco', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Jutiapa', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'San Isidro (Cabañas)', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Sensuntepeque', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Tejutepeque', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Victoria', 'departamento_id' => '9']);
        Municipio::create(['nombre' => 'Apastepeque', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Guadalupe', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Cayetano Istepeque', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Esteban Catarina', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Ildefonso', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Lorenzo', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Sebastián', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'San Vicente', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Santa Clara', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Santo Domingo', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Tecoluca', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Tepetitán', 'departamento_id' => '10']);
        Municipio::create(['nombre' => 'Verapaz', 'departamento_id' => '10']);
    }
}
